"""agrega llaves foraneas en rutas de aprendizaje

Revision ID: 13f895cf840d
Revises: 2ee7ae1fa711
Create Date: 2026-08-22 18:10:10.230001

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13f895cf840d"
down_revision: Union[str, Sequence[str], None] = "2ee7ae1fa711"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "learning_paths", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "learning_paths", type_="foreignkey")
    # ### end Alembic commands ###
