"""rutas de aprendizaje

Revision ID: 2ee7ae1fa711
Revises: fc1fd01147ba
Create Date: 2026-08-22 18:05:34.507671

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ee7ae1fa711"
down_revision: Union[str, Sequence[str], None] = "fc1fd01147ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "learning_path_contents", "learning_paths", ["learning_path_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "learning_path_contents", type_="foreignkey")
    # ### end Alembic commands ###
