"""agrega llave foranea de contenido

Revision ID: 4cc5f30b1eee
Revises: 13f895cf840d
Create Date: 2026-08-22 18:12:37.997075

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cc5f30b1eee"
down_revision: Union[str, Sequence[str], None] = "13f895cf840d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "learning_path_contents", "contents", ["content_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "learning_path_contents", type_="foreignkey")
    # ### end Alembic commands ###
