"""agrega nombre a usuario

Revision ID: 6639a17b9dd2
Revises: 4cc5f30b1eee
Create Date: 2026-08-29 13:17:06.741513

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6639a17b9dd2"
down_revision: Union[str, Sequence[str], None] = "4cc5f30b1eee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String()))

    op.execute("UPDATE users SET name = username")

    op.alter_column("users", "name", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name")
    # ### end Alembic commands ###
