"""rutas de aprendizaje

Revision ID: fc1fd01147ba
Revises: fb7fb976a2c1
Create Date: 2026-08-22 17:59:02.918749

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fc1fd01147ba"
down_revision: Union[str, Sequence[str], None] = "fb7fb976a2c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_path_contents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("learning_path_id", sa.String(), nullable=False),
        sa.Column("content_id", sa.String(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_path_contents_content_id"),
        "learning_path_contents",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_path_contents_id"),
        "learning_path_contents",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_path_contents_learning_path_id"),
        "learning_path_contents",
        ["learning_path_id"],
        unique=False,
    )
    op.create_table(
        "learning_paths",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_paths_id"), "learning_paths", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_learning_paths_topic"), "learning_paths", ["topic"], unique=False
    )
    op.create_index(
        op.f("ix_learning_paths_user_id"), "learning_paths", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_learning_paths_user_id"), table_name="learning_paths")
    op.drop_index(op.f("ix_learning_paths_topic"), table_name="learning_paths")
    op.drop_index(op.f("ix_learning_paths_id"), table_name="learning_paths")
    op.drop_table("learning_paths")
    op.drop_index(
        op.f("ix_learning_path_contents_learning_path_id"),
        table_name="learning_path_contents",
    )
    op.drop_index(
        op.f("ix_learning_path_contents_id"), table_name="learning_path_contents"
    )
    op.drop_index(
        op.f("ix_learning_path_contents_content_id"),
        table_name="learning_path_contents",
    )
    op.drop_table("learning_path_contents")
    # ### end Alembic commands ###
